all:
  root_dir: "/path/to/root/dir"
  output_dir: "output"
  sample_list: "/path/to/samples.tsv"

align:
  seq_method: "illumina" # ["illumina", "ont"]
  target_fasta: "/path/to/reference.fasta"
  #target_fasta: "reference/MN985325_1.fasta" # SARS-CoV-2 reference
