name: workflow-test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Test workflow
        run: |
          wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
          START_DIR=$(pwd)
          bash Miniconda3-latest-Linux-x86_64.sh -b -p $START_DIR/miniconda3
          export PATH=${PATH}:$START_DIR/miniconda3/bin
          CONDA_BASE=$(conda info --base)
          source $CONDA_BASE/etc/profile.d/conda.sh
          conda create -n wf_test
          conda activate wf_test
          conda install -qy snakemake -c conda-forge
          cd example
          snakemake all_summarize --use-conda -p --snakefile ../Snakefile --configfile example_config.yml
